/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BlockGetDetailsResponseHeading2RichTextInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BlockGetDetailsResponseHeading2
 */
public class BlockGetDetailsResponseHeading2Test {
    private final BlockGetDetailsResponseHeading2 model = new BlockGetDetailsResponseHeading2();

    /**
     * Model tests for BlockGetDetailsResponseHeading2
     */
    @Test
    public void testBlockGetDetailsResponseHeading2() {
        // TODO: test BlockGetDetailsResponseHeading2
    }

    /**
     * Test the property 'richText'
     */
    @Test
    public void richTextTest() {
        // TODO: test richText
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'isToggleable'
     */
    @Test
    public void isToggleableTest() {
        // TODO: test isToggleable
    }

}
