/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DatabaseGetDatabaseResponsePropertiesInStock
 */
public class DatabaseGetDatabaseResponsePropertiesInStockTest {
    private final DatabaseGetDatabaseResponsePropertiesInStock model = new DatabaseGetDatabaseResponsePropertiesInStock();

    /**
     * Model tests for DatabaseGetDatabaseResponsePropertiesInStock
     */
    @Test
    public void testDatabaseGetDatabaseResponsePropertiesInStock() {
        // TODO: test DatabaseGetDatabaseResponsePropertiesInStock
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'checkbox'
     */
    @Test
    public void checkboxTest() {
        // TODO: test checkbox
    }

}
