/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
 */
public class DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollupTest {
    private final DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup model = new DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup();

    /**
     * Model tests for DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
     */
    @Test
    public void testDatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup() {
        // TODO: test DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
    }

    /**
     * Test the property 'rollupPropertyName'
     */
    @Test
    public void rollupPropertyNameTest() {
        // TODO: test rollupPropertyName
    }

    /**
     * Test the property 'relationPropertyName'
     */
    @Test
    public void relationPropertyNameTest() {
        // TODO: test relationPropertyName
    }

    /**
     * Test the property 'rollupPropertyId'
     */
    @Test
    public void rollupPropertyIdTest() {
        // TODO: test rollupPropertyId
    }

    /**
     * Test the property 'relationPropertyId'
     */
    @Test
    public void relationPropertyIdTest() {
        // TODO: test relationPropertyId
    }

    /**
     * Test the property 'function'
     */
    @Test
    public void functionTest() {
        // TODO: test function
    }

}
