/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DatabaseGetDatabaseResponseProperties1;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesDescription;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesFoodGroup;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesInStock;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesLastOrdered;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesMeals;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesName;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesNumberOfMeals;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesPhoto;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesPrice;
import com.konfigthis.client.model.DatabaseGetDatabaseResponsePropertiesStoreAvailability;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DatabaseGetDatabaseResponseProperties
 */
public class DatabaseGetDatabaseResponsePropertiesTest {
    private final DatabaseGetDatabaseResponseProperties model = new DatabaseGetDatabaseResponseProperties();

    /**
     * Model tests for DatabaseGetDatabaseResponseProperties
     */
    @Test
    public void testDatabaseGetDatabaseResponseProperties() {
        // TODO: test DatabaseGetDatabaseResponseProperties
    }

    /**
     * Test the property 'plus1'
     */
    @Test
    public void plus1Test() {
        // TODO: test plus1
    }

    /**
     * Test the property 'inStock'
     */
    @Test
    public void inStockTest() {
        // TODO: test inStock
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'lastOrdered'
     */
    @Test
    public void lastOrderedTest() {
        // TODO: test lastOrdered
    }

    /**
     * Test the property 'meals'
     */
    @Test
    public void mealsTest() {
        // TODO: test meals
    }

    /**
     * Test the property 'numberOfMeals'
     */
    @Test
    public void numberOfMealsTest() {
        // TODO: test numberOfMeals
    }

    /**
     * Test the property 'storeAvailability'
     */
    @Test
    public void storeAvailabilityTest() {
        // TODO: test storeAvailability
    }

    /**
     * Test the property 'photo'
     */
    @Test
    public void photoTest() {
        // TODO: test photo
    }

    /**
     * Test the property 'foodGroup'
     */
    @Test
    public void foodGroupTest() {
        // TODO: test foodGroup
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
