/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PageCreateNewPageResponseCover;
import com.konfigthis.client.model.PageCreateNewPageResponseCreatedBy;
import com.konfigthis.client.model.PageCreateNewPageResponseIcon;
import com.konfigthis.client.model.PageCreateNewPageResponseLastEditedBy;
import com.konfigthis.client.model.PageCreateNewPageResponseParent;
import com.konfigthis.client.model.PageCreateNewPageResponseProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PageCreateNewPageResponse
 */
public class PageCreateNewPageResponseTest {
    private final PageCreateNewPageResponse model = new PageCreateNewPageResponse();

    /**
     * Model tests for PageCreateNewPageResponse
     */
    @Test
    public void testPageCreateNewPageResponse() {
        // TODO: test PageCreateNewPageResponse
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdTime'
     */
    @Test
    public void createdTimeTest() {
        // TODO: test createdTime
    }

    /**
     * Test the property 'lastEditedTime'
     */
    @Test
    public void lastEditedTimeTest() {
        // TODO: test lastEditedTime
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'lastEditedBy'
     */
    @Test
    public void lastEditedByTest() {
        // TODO: test lastEditedBy
    }

    /**
     * Test the property 'cover'
     */
    @Test
    public void coverTest() {
        // TODO: test cover
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'parent'
     */
    @Test
    public void parentTest() {
        // TODO: test parent
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
