/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesCostOfNextTrip;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesDescription;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesFoodGroup;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesInStock;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesLastOrdered;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesName;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesNumberOfMeals;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesPhoto;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesPrice;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesRecipes;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesResponsiblePerson;
import com.konfigthis.client.model.PageUpdatePropertiesResponsePropertiesStoreAvailability;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PageUpdatePropertiesResponseProperties
 */
public class PageUpdatePropertiesResponsePropertiesTest {
    private final PageUpdatePropertiesResponseProperties model = new PageUpdatePropertiesResponseProperties();

    /**
     * Model tests for PageUpdatePropertiesResponseProperties
     */
    @Test
    public void testPageUpdatePropertiesResponseProperties() {
        // TODO: test PageUpdatePropertiesResponseProperties
    }

    /**
     * Test the property 'storeAvailability'
     */
    @Test
    public void storeAvailabilityTest() {
        // TODO: test storeAvailability
    }

    /**
     * Test the property 'foodGroup'
     */
    @Test
    public void foodGroupTest() {
        // TODO: test foodGroup
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'responsiblePerson'
     */
    @Test
    public void responsiblePersonTest() {
        // TODO: test responsiblePerson
    }

    /**
     * Test the property 'lastOrdered'
     */
    @Test
    public void lastOrderedTest() {
        // TODO: test lastOrdered
    }

    /**
     * Test the property 'costOfNextTrip'
     */
    @Test
    public void costOfNextTripTest() {
        // TODO: test costOfNextTrip
    }

    /**
     * Test the property 'recipes'
     */
    @Test
    public void recipesTest() {
        // TODO: test recipes
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'inStock'
     */
    @Test
    public void inStockTest() {
        // TODO: test inStock
    }

    /**
     * Test the property 'numberOfMeals'
     */
    @Test
    public void numberOfMealsTest() {
        // TODO: test numberOfMeals
    }

    /**
     * Test the property 'photo'
     */
    @Test
    public void photoTest() {
        // TODO: test photo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
