/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SearchByTitleResponseResultsInnerParent
 */
public class SearchByTitleResponseResultsInnerParentTest {
    private final SearchByTitleResponseResultsInnerParent model = new SearchByTitleResponseResultsInnerParent();

    /**
     * Model tests for SearchByTitleResponseResultsInnerParent
     */
    @Test
    public void testSearchByTitleResponseResultsInnerParent() {
        // TODO: test SearchByTitleResponseResultsInnerParent
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'databaseId'
     */
    @Test
    public void databaseIdTest() {
        // TODO: test databaseId
    }

}
