/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SearchByTitleResponseResultsInnerPropertiesNameTitleInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SearchByTitleResponseResultsInnerPropertiesName
 */
public class SearchByTitleResponseResultsInnerPropertiesNameTest {
    private final SearchByTitleResponseResultsInnerPropertiesName model = new SearchByTitleResponseResultsInnerPropertiesName();

    /**
     * Model tests for SearchByTitleResponseResultsInnerPropertiesName
     */
    @Test
    public void testSearchByTitleResponseResultsInnerPropertiesName() {
        // TODO: test SearchByTitleResponseResultsInnerPropertiesName
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
