/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SearchByTitleResponseResultsInnerPropertiesNameTitleInnerAnnotations;
import com.konfigthis.client.model.SearchByTitleResponseResultsInnerPropertiesNameTitleInnerText;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SearchByTitleResponseResultsInnerPropertiesNameTitleInner
 */
public class SearchByTitleResponseResultsInnerPropertiesNameTitleInnerTest {
    private final SearchByTitleResponseResultsInnerPropertiesNameTitleInner model = new SearchByTitleResponseResultsInnerPropertiesNameTitleInner();

    /**
     * Model tests for SearchByTitleResponseResultsInnerPropertiesNameTitleInner
     */
    @Test
    public void testSearchByTitleResponseResultsInnerPropertiesNameTitleInner() {
        // TODO: test SearchByTitleResponseResultsInnerPropertiesNameTitleInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'annotations'
     */
    @Test
    public void annotationsTest() {
        // TODO: test annotations
    }

    /**
     * Test the property 'plainText'
     */
    @Test
    public void plainTextTest() {
        // TODO: test plainText
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

}
