/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TokenGenerateAccessResponseOwner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TokenGenerateAccessResponse
 */
public class TokenGenerateAccessResponseTest {
    private final TokenGenerateAccessResponse model = new TokenGenerateAccessResponse();

    /**
     * Model tests for TokenGenerateAccessResponse
     */
    @Test
    public void testTokenGenerateAccessResponse() {
        // TODO: test TokenGenerateAccessResponse
    }

    /**
     * Test the property 'accessToken'
     */
    @Test
    public void accessTokenTest() {
        // TODO: test accessToken
    }

    /**
     * Test the property 'botId'
     */
    @Test
    public void botIdTest() {
        // TODO: test botId
    }

    /**
     * Test the property 'duplicatedTemplateId'
     */
    @Test
    public void duplicatedTemplateIdTest() {
        // TODO: test duplicatedTemplateId
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'workspaceIcon'
     */
    @Test
    public void workspaceIconTest() {
        // TODO: test workspaceIcon
    }

    /**
     * Test the property 'workspaceId'
     */
    @Test
    public void workspaceIdTest() {
        // TODO: test workspaceId
    }

    /**
     * Test the property 'workspaceName'
     */
    @Test
    public void workspaceNameTest() {
        // TODO: test workspaceName
    }

}
