/*
 * Notion API
 * Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup {
  public static final String SERIALIZED_NAME_ROLLUP_PROPERTY_NAME = "rollup_property_name";
  @SerializedName(SERIALIZED_NAME_ROLLUP_PROPERTY_NAME)
  private String rollupPropertyName;

  public static final String SERIALIZED_NAME_RELATION_PROPERTY_NAME = "relation_property_name";
  @SerializedName(SERIALIZED_NAME_RELATION_PROPERTY_NAME)
  private String relationPropertyName;

  public static final String SERIALIZED_NAME_ROLLUP_PROPERTY_ID = "rollup_property_id";
  @SerializedName(SERIALIZED_NAME_ROLLUP_PROPERTY_ID)
  private String rollupPropertyId;

  public static final String SERIALIZED_NAME_RELATION_PROPERTY_ID = "relation_property_id";
  @SerializedName(SERIALIZED_NAME_RELATION_PROPERTY_ID)
  private String relationPropertyId;

  public static final String SERIALIZED_NAME_FUNCTION = "function";
  @SerializedName(SERIALIZED_NAME_FUNCTION)
  private String function;

  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup() {
  }

  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup rollupPropertyName(String rollupPropertyName) {
    
    
    
    
    this.rollupPropertyName = rollupPropertyName;
    return this;
  }

   /**
   * Get rollupPropertyName
   * @return rollupPropertyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Name", value = "")

  public String getRollupPropertyName() {
    return rollupPropertyName;
  }


  public void setRollupPropertyName(String rollupPropertyName) {
    
    
    
    this.rollupPropertyName = rollupPropertyName;
  }


  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup relationPropertyName(String relationPropertyName) {
    
    
    
    
    this.relationPropertyName = relationPropertyName;
    return this;
  }

   /**
   * Get relationPropertyName
   * @return relationPropertyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Meals", value = "")

  public String getRelationPropertyName() {
    return relationPropertyName;
  }


  public void setRelationPropertyName(String relationPropertyName) {
    
    
    
    this.relationPropertyName = relationPropertyName;
  }


  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup rollupPropertyId(String rollupPropertyId) {
    
    
    
    
    this.rollupPropertyId = rollupPropertyId;
    return this;
  }

   /**
   * Get rollupPropertyId
   * @return rollupPropertyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "title", value = "")

  public String getRollupPropertyId() {
    return rollupPropertyId;
  }


  public void setRollupPropertyId(String rollupPropertyId) {
    
    
    
    this.rollupPropertyId = rollupPropertyId;
  }


  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup relationPropertyId(String relationPropertyId) {
    
    
    
    
    this.relationPropertyId = relationPropertyId;
    return this;
  }

   /**
   * Get relationPropertyId
   * @return relationPropertyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "mxp^", value = "")

  public String getRelationPropertyId() {
    return relationPropertyId;
  }


  public void setRelationPropertyId(String relationPropertyId) {
    
    
    
    this.relationPropertyId = relationPropertyId;
  }


  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup function(String function) {
    
    
    
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "count", value = "")

  public String getFunction() {
    return function;
  }


  public void setFunction(String function) {
    
    
    
    this.function = function;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup instance itself
   */
  public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup databaseGetDatabaseResponsePropertiesNumberOfMealsRollup = (DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup) o;
    return Objects.equals(this.rollupPropertyName, databaseGetDatabaseResponsePropertiesNumberOfMealsRollup.rollupPropertyName) &&
        Objects.equals(this.relationPropertyName, databaseGetDatabaseResponsePropertiesNumberOfMealsRollup.relationPropertyName) &&
        Objects.equals(this.rollupPropertyId, databaseGetDatabaseResponsePropertiesNumberOfMealsRollup.rollupPropertyId) &&
        Objects.equals(this.relationPropertyId, databaseGetDatabaseResponsePropertiesNumberOfMealsRollup.relationPropertyId) &&
        Objects.equals(this.function, databaseGetDatabaseResponsePropertiesNumberOfMealsRollup.function)&&
        Objects.equals(this.additionalProperties, databaseGetDatabaseResponsePropertiesNumberOfMealsRollup.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rollupPropertyName, relationPropertyName, rollupPropertyId, relationPropertyId, function, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup {\n");
    sb.append("    rollupPropertyName: ").append(toIndentedString(rollupPropertyName)).append("\n");
    sb.append("    relationPropertyName: ").append(toIndentedString(relationPropertyName)).append("\n");
    sb.append("    rollupPropertyId: ").append(toIndentedString(rollupPropertyId)).append("\n");
    sb.append("    relationPropertyId: ").append(toIndentedString(relationPropertyId)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rollup_property_name");
    openapiFields.add("relation_property_name");
    openapiFields.add("rollup_property_id");
    openapiFields.add("relation_property_id");
    openapiFields.add("function");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup is not found in the empty JSON string", DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("rollup_property_name") != null && !jsonObj.get("rollup_property_name").isJsonNull()) && !jsonObj.get("rollup_property_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rollup_property_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rollup_property_name").toString()));
      }
      if ((jsonObj.get("relation_property_name") != null && !jsonObj.get("relation_property_name").isJsonNull()) && !jsonObj.get("relation_property_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relation_property_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relation_property_name").toString()));
      }
      if ((jsonObj.get("rollup_property_id") != null && !jsonObj.get("rollup_property_id").isJsonNull()) && !jsonObj.get("rollup_property_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rollup_property_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rollup_property_id").toString()));
      }
      if ((jsonObj.get("relation_property_id") != null && !jsonObj.get("relation_property_id").isJsonNull()) && !jsonObj.get("relation_property_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relation_property_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relation_property_id").toString()));
      }
      if ((jsonObj.get("function") != null && !jsonObj.get("function").isJsonNull()) && !jsonObj.get("function").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `function` to be a primitive type in the JSON string but got `%s`", jsonObj.get("function").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup.class));

       return (TypeAdapter<T>) new TypeAdapter<DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup>() {
           @Override
           public void write(JsonWriter out, DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
  * @throws IOException if the JSON string is invalid with respect to DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup
  */
  public static DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup.class);
  }

 /**
  * Convert an instance of DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

